# Generated by Django 5.1.4 on 2024-12-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="question",
            table="quiz_questions",
        ),
    ]
