# Generated by Django 5.1.4 on 2024-12-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_question_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("QuesText", models.CharField(max_length=255)),
                ("OptionA", models.CharField(max_length=100)),
                ("OptionB", models.CharField(max_length=100)),
                ("OptionC", models.CharField(max_length=100)),
                ("OptionD", models.CharField(max_length=100)),
                ("OptionAns", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "quiz_question",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("current_question_index", models.IntegerField(default=0)),
                ("score", models.IntegerField()),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
