# Generated by Django 5.1.4 on 2024-12-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_quizquestions_usersession_delete_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestions",
            name="id",
        ),
        migrations.AddField(
            model_name="quizquestions",
            name="question_id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
