# Generated by Django 5.1.4 on 2024-12-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_remove_quizquestions_id_quizquestions_question_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestions",
            name="question_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
